// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpcddpxbmnttwdqfrrtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwY2RkcHhibW50dHdkcWZycnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTgyMjEsImV4cCI6MjA2MDI3NDIyMX0.Iv0atQQ4jzHNgMiXomel4c1O4gD_NqUrcDjzfEuXoPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);